// quotes.js — The Daily Reset Quote Library
// One unified "Daily Quote" rotates across the dashboard card, the once-daily
// splash, and the closing quote after every break — no longer tied to which
// break topic just finished. Pool: 488 famous-figure quotes (daily) + the
// original 30 break-specific + 12 general quotes, all kept as extra variety
// on top of the new set, interleaved proportionally with the 6 faith quotes.
// Criteria: substance, attribution — "(attributed)" marks quotes that are
// widely circulated but not confidently sourced to a primary text.

const QUOTES = {
  daily: [
    { text: 'Your time is limited, so don\'t waste it living someone else\'s life.', author: 'Steve Jobs' },
    { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
    { text: 'Stay hungry, stay foolish.', author: 'Steve Jobs' },
    { text: 'Sometimes life is going to hit you in the head with a brick. Don\'t lose faith.', author: 'Steve Jobs' },
    { text: 'Whatever it takes, whatever you have to do, however you have to do it, you must find a way to feed your mind positive input.', author: 'Tony Robbins' },
    { text: 'It\'s not knowing what to do, it\'s doing what you know.', author: 'Tony Robbins' },
    { text: 'The only impossible journey is the one you never begin.', author: 'Tony Robbins' },
    { text: 'Setting goals is the first step in turning the invisible into the visible.', author: 'Tony Robbins' },
    { text: 'Just keep livin\'.', author: 'Matthew McConaughey' },
    { text: 'When you\'ve got something to prove, there\'s nothing more dangerous than a man who knows the truth and doesn\'t back down.', author: 'Matthew McConaughey' },
    { text: 'The best advice comes from people who don\'t give advice for a living.', author: 'Matthew McConaughey' },
    { text: 'It\'s a fine line between an ego that\'s too big and confidence, and I think that gap gets finer the higher up you go.', author: 'Matthew McConaughey' },
    { text: 'We each need to find our own inspiration. Sometimes it\'s not obvious.', author: 'Morgan Freeman' },
    { text: 'Every day I wake up and decide, today I\'m going to make somebody happy or affect somebody\'s life in a positive way.', author: 'Morgan Freeman' },
    { text: 'The best thing about being an actor is you never know when you\'re going to be doing something you love.', author: 'Morgan Freeman' },
    { text: 'You have to keep pushing. That\'s the key to everything.', author: 'Morgan Freeman' },
    { text: 'Price is what you pay. Value is what you get.', author: 'Warren Buffett' },
    { text: 'The most important investment you can make is in yourself.', author: 'Warren Buffett' },
    { text: 'It takes 20 years to build a reputation and five minutes to ruin it.', author: 'Warren Buffett' },
    { text: 'Someone\'s sitting in the shade today because someone planted a tree a long time ago.', author: 'Warren Buffett' },
    { text: 'Risk comes from not knowing what you\'re doing.', author: 'Warren Buffett' },
    { text: 'Faith is taking the first step even when you don\'t see the whole staircase.', author: 'Martin Luther King Jr.' },
    { text: 'Darkness cannot drive out darkness; only light can do that.', author: 'Martin Luther King Jr.' },
    { text: 'The time is always right to do what is right.', author: 'Martin Luther King Jr.' },
    { text: 'Our lives begin to end the day we become silent about things that matter.', author: 'Martin Luther King Jr.' },
    { text: 'If you can\'t fly then run, if you can\'t run then walk, if you can\'t walk then crawl, but whatever you do you have to keep moving forward.', author: 'Martin Luther King Jr.' },
    { text: 'It always seems impossible until it\'s done.', author: 'Nelson Mandela' },
    { text: 'I never lose. I either win or learn.', author: 'Nelson Mandela' },
    { text: 'A good head and a good heart are always a formidable combination.', author: 'Nelson Mandela' },
    { text: 'Education is the most powerful weapon which you can use to change the world.', author: 'Nelson Mandela' },
    { text: 'It is not our differences that divide us. It is our inability to recognize, accept, and celebrate those differences.', author: 'Nelson Mandela' },
    { text: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney' },
    { text: 'All our dreams can come true if we have the courage to pursue them.', author: 'Walt Disney' },
    { text: 'It\'s kind of fun to do the impossible.', author: 'Walt Disney' },
    { text: 'If you can dream it, you can do it.', author: 'Walt Disney' },
    { text: 'I have not failed. I\'ve just found 10,000 ways that won\'t work.', author: 'Thomas Edison' },
    { text: 'Genius is one percent inspiration and ninety-nine percent perspiration.', author: 'Thomas Edison' },
    { text: 'Many of life\'s failures are people who did not realize how close they were to success when they gave up.', author: 'Thomas Edison' },
    { text: 'The way I see it, if you want the rainbow, you gotta put up with the rain.', author: 'Dolly Parton' },
    { text: 'Figure out who you are, and do it on purpose.', author: 'Dolly Parton' },
    { text: 'If you don\'t like the road you\'re walking, start paving another one.', author: 'Dolly Parton' },
    { text: 'Never let a stumble in the road be the end of the journey.', author: 'Dolly Parton' },
    { text: 'You can\'t use up creativity. The more you use, the more you have.', author: 'Maya Angelou' },
    { text: 'If you don\'t like something, change it. If you can\'t change it, change your attitude.', author: 'Maya Angelou' },
    { text: 'Try to be a rainbow in someone else\'s cloud.', author: 'Maya Angelou' },
    { text: 'Success is liking yourself, liking what you do, and liking how you do it.', author: 'Maya Angelou' },
    { text: 'Nothing will work unless you do.', author: 'Maya Angelou' },
    { text: 'The best way to predict the future is to create it.', author: 'Abraham Lincoln' },
    { text: 'Whatever you are, be a good one.', author: 'Abraham Lincoln' },
    { text: 'I am a slow walker, but I never walk back.', author: 'Abraham Lincoln' },
    { text: 'Always bear in mind that your own resolution to succeed is more important than any other one thing.', author: 'Abraham Lincoln' },
    { text: 'Do the one thing you think you cannot do. Fail at it. Try again.', author: 'Oprah Winfrey' },
    { text: 'The biggest adventure you can take is to live the life of your dreams.', author: 'Oprah Winfrey' },
    { text: 'Turn your wounds into wisdom.', author: 'Oprah Winfrey' },
    { text: 'Passion is energy. Feel the power that comes from focusing on what excites you.', author: 'Oprah Winfrey' },
    { text: 'Real integrity is doing the right thing, knowing that nobody\'s going to know whether you did it or not.', author: 'Oprah Winfrey' },
    { text: 'It always seems impossible until it\'s done — but you find that out only by starting.', author: 'Muhammad Ali' },
    { text: 'Champions aren\'t made in gyms. Champions are made from something they have deep inside them — a desire, a dream, a vision.', author: 'Muhammad Ali' },
    { text: 'He who is not courageous enough to take risks will accomplish nothing in life.', author: 'Muhammad Ali' },
    { text: 'Don\'t count the days, make the days count.', author: 'Muhammad Ali' },
    { text: 'Service to others is the rent you pay for your room here on earth.', author: 'Muhammad Ali' },
    { text: 'You miss 100% of the shots you don\'t take.', author: 'Wayne Gretzky' },
    { text: 'I skate to where the puck is going to be, not where it has been.', author: 'Wayne Gretzky' },
    { text: 'I\'ve missed more than 9,000 shots in my career. I\'ve lost almost 300 games. I\'ve failed over and over again — and that is why I succeed.', author: 'Michael Jordan' },
    { text: 'Talent wins games, but teamwork and intelligence win championships.', author: 'Michael Jordan' },
    { text: 'Obstacles don\'t have to stop you. If you run into a wall, don\'t turn around and give up. Figure out how to climb it.', author: 'Michael Jordan' },
    { text: 'Some people want it to happen, some wish it would happen, others make it happen.', author: 'Michael Jordan' },
    { text: 'It\'s not whether you get knocked down, it\'s whether you get up.', author: 'Vince Lombardi' },
    { text: 'The measure of who we are is what we do with what we have.', author: 'Vince Lombardi' },
    { text: 'Winning isn\'t everything, but wanting to win is.', author: 'Vince Lombardi' },
    { text: 'You have to be odd to be number one.', author: 'Dr. Seuss' },
    { text: 'Today you are you, that is truer than true. There is no one alive who is youer than you.', author: 'Dr. Seuss' },
    { text: 'Sometimes you will never know the value of a moment until it becomes a memory.', author: 'Dr. Seuss' },
    { text: 'I am not afraid of storms, for I am learning how to sail my ship.', author: 'Louisa May Alcott' },
    { text: 'Far away there in the sunshine are my highest aspirations. I may not reach them, but I can look up and see their beauty.', author: 'Louisa May Alcott' },
    { text: 'The two most important days in your life are the day you are born and the day you find out why.', author: 'Mark Twain' },
    { text: 'Twenty years from now you will be more disappointed by the things you didn\'t do than by the ones you did do.', author: 'Mark Twain' },
    { text: 'Courage is resistance to fear, mastery of fear — not absence of fear.', author: 'Mark Twain' },
    { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
    { text: 'It is not the strongest of the species that survives, but the one most responsive to change.', author: 'Charles Darwin' },
    { text: 'A man who dares to waste one hour of time has not discovered the value of life.', author: 'Charles Darwin' },
    { text: 'If I have seen further, it is by standing on the shoulders of giants.', author: 'Isaac Newton' },
    { text: 'Tact is the art of making a point without making an enemy.', author: 'Isaac Newton' },
    { text: 'The important thing is not to stop questioning. Curiosity has its own reason for existing.', author: 'Albert Einstein' },
    { text: 'In the middle of difficulty lies opportunity.', author: 'Albert Einstein' },
    { text: 'Try not to become a person of success, but rather try to become a person of value.', author: 'Albert Einstein' },
    { text: 'Once we accept our limits, we go beyond them.', author: 'Albert Einstein' },
    { text: 'Logic will get you from A to B. Imagination will take you everywhere.', author: 'Albert Einstein' },
    { text: 'The scientist is not the one who provides the right answers; he\'s the one who asks the right questions.', author: 'Claude Levi-Strauss' },
    { text: 'Science knows no country, because knowledge belongs to humanity.', author: 'Louis Pasteur' },
    { text: 'Chance favors only the prepared mind.', author: 'Louis Pasteur' },
    { text: 'I have learned over the years that when one\'s mind is made up, this diminishes fear.', author: 'Rosa Parks' },
    { text: 'You must never be fearful about what you are doing when it is right.', author: 'Rosa Parks' },
    { text: 'Each person must live their life as a model for others.', author: 'Rosa Parks' },
    { text: 'I\'m no longer accepting the things I cannot change. I\'m changing the things I cannot accept.', author: 'Angela Davis' },
    { text: 'You can\'t build a reputation on what you are going to do.', author: 'Henry Ford' },
    { text: 'Whether you think you can, or you think you can\'t — you\'re right.', author: 'Henry Ford' },
    { text: 'Failure is simply the opportunity to begin again, this time more intelligently.', author: 'Henry Ford' },
    { text: 'Coming together is a beginning; keeping together is progress; working together is success.', author: 'Henry Ford' },
    { text: 'Anyone who has never made a mistake has never tried anything new.', author: 'Albert Einstein' },
    { text: 'If you\'re going through hell, keep going.', author: 'Winston Churchill' },
    { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill' },
    { text: 'Attitude is a little thing that makes a big difference.', author: 'Winston Churchill' },
    { text: 'We make a living by what we get, but we make a life by what we give.', author: 'Winston Churchill' },
    { text: 'To improve is to change; to be perfect is to change often.', author: 'Winston Churchill' },
    { text: 'In the depth of winter, I finally learned that within me there lay an invincible summer.', author: 'Albert Camus' },
    { text: 'Life is 10% what happens to you and 90% how you react to it.', author: 'Charles R. Swindoll' },
    { text: 'Believe you can and you\'re halfway there.', author: 'Theodore Roosevelt' },
    { text: 'It is hard to fail, but it is worse never to have tried to succeed.', author: 'Theodore Roosevelt' },
    { text: 'Comparison is the thief of joy.', author: 'Theodore Roosevelt' },
    { text: 'Do what you can, with what you have, where you are.', author: 'Theodore Roosevelt' },
    { text: 'Far better is it to dare mighty things, to win glorious triumphs, even though checkered by failure, than to rank with those poor spirits who neither enjoy much nor suffer much.', author: 'Theodore Roosevelt' },
    { text: 'Change your thoughts and you change your world.', author: 'Norman Vincent Peale' },
    { text: 'Shoot for the moon. Even if you miss, you\'ll land among the stars.', author: 'Norman Vincent Peale' },
    { text: 'Action is the foundational key to all success.', author: 'Pablo Picasso' },
    { text: 'Every child is an artist. The problem is how to remain an artist once we grow up.', author: 'Pablo Picasso' },
    { text: 'The meaning of life is to find your gift. The purpose of life is to give it away.', author: 'Pablo Picasso' },
    { text: 'Success is walking from failure to failure with no loss of enthusiasm.', author: 'Winston Churchill' },
    { text: 'In three words I can sum up everything I\'ve learned about life: it goes on.', author: 'Robert Frost' },
    { text: 'Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.', author: 'Robert Frost' },
    { text: 'The woods are lovely, dark and deep, but I have promises to keep, and miles to go before I sleep.', author: 'Robert Frost' },
    { text: 'Freedom lies in being bold.', author: 'Robert Frost' },
    { text: 'Do not go where the path may lead, go instead where there is no path and leave a trail.', author: 'Ralph Waldo Emerson (attributed)' },
    { text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson' },
    { text: 'The only person you are destined to become is the person you decide to be.', author: 'Ralph Waldo Emerson' },
    { text: 'For every minute you remain angry, you give up sixty seconds of peace of mind.', author: 'Ralph Waldo Emerson' },
    { text: 'Life is not a problem to be solved, but a reality to be experienced.', author: 'Soren Kierkegaard' },
    { text: 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', author: 'Ralph Waldo Emerson (attributed)' },
    { text: 'Our greatest glory is not in never falling, but in rising every time we fall.', author: 'Confucius (attributed)' },
    { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius (attributed)' },
    { text: 'The man who moves a mountain begins by carrying away small stones.', author: 'Confucius (attributed)' },
    { text: 'Real knowledge is to know the extent of one\'s ignorance.', author: 'Confucius (attributed)' },
    { text: 'Wherever you go, go with all your heart.', author: 'Confucius (attributed)' },
    { text: 'The journey of a thousand miles begins with a single step.', author: 'Lao Tzu (attributed)' },
    { text: 'A good traveler has no fixed plans and is not intent on arriving.', author: 'Lao Tzu (attributed)' },
    { text: 'Nature does not hurry, yet everything is accomplished.', author: 'Lao Tzu (attributed)' },
    { text: 'Knowing others is wisdom, knowing yourself is enlightenment.', author: 'Lao Tzu (attributed)' },
    { text: 'New beginnings are often disguised as painful endings.', author: 'Lao Tzu (attributed)' },
    { text: 'There is no way to happiness — happiness is the way.', author: 'Thich Nhat Hanh' },
    { text: 'Fall seven times, stand up eight.', author: 'Japanese Proverb' },
    { text: 'A smooth sea never made a skilled sailor.', author: 'African Proverb' },
    { text: 'However far you have gone on a wrong road, turn back.', author: 'Turkish Proverb' },
    { text: 'If you want to go fast, go alone. If you want to go far, go together.', author: 'African Proverb' },
    { text: 'The best preparation for tomorrow is doing your best today.', author: 'H. Jackson Brown Jr.' },
    { text: 'Twenty years from now you\'ll wish you had started today.', author: 'Karen Lamb' },
    { text: 'Opportunities don\'t happen. You create them.', author: 'Chris Grosser' },
    { text: 'Don\'t wait for opportunity. Create it.', author: 'George Bernard Shaw' },
    { text: 'Life isn\'t about finding yourself. Life is about creating yourself.', author: 'George Bernard Shaw' },
    { text: 'Progress is impossible without change, and those who cannot change their minds cannot change anything.', author: 'George Bernard Shaw' },
    { text: 'The reasonable man adapts himself to the world; the unreasonable one persists in trying to adapt the world to himself.', author: 'George Bernard Shaw' },
    { text: 'Life shrinks or expands in proportion to one\'s courage.', author: 'Anais Nin' },
    { text: 'And the day came when the risk to remain tight in a bud was more painful than the risk it took to blossom.', author: 'Anais Nin' },
    { text: 'We don\'t see things as they are, we see them as we are.', author: 'Anais Nin' },
    { text: 'What you get by achieving your goals is not as important as what you become by achieving your goals.', author: 'Zig Ziglar' },
    { text: 'You don\'t have to be great to start, but you have to start to be great.', author: 'Zig Ziglar' },
    { text: 'People often say that motivation doesn\'t last. Well, neither does bathing — that\'s why we recommend it daily.', author: 'Zig Ziglar' },
    { text: 'Success occurs when opportunity meets preparation.', author: 'Zig Ziglar' },
    { text: 'The starting point of all achievement is desire.', author: 'Napoleon Hill' },
    { text: 'Whatever the mind can conceive and believe, it can achieve.', author: 'Napoleon Hill' },
    { text: 'Set your mind on a definite goal and observe how quickly the world stands aside to let you pass.', author: 'Napoleon Hill' },
    { text: 'Effort only fully releases its reward after a person refuses to quit.', author: 'Napoleon Hill' },
    { text: 'Formal education will make you a living; self-education will make you a fortune.', author: 'Jim Rohn' },
    { text: 'You are the average of the five people you spend the most time with.', author: 'Jim Rohn' },
    { text: 'Discipline is the bridge between goals and accomplishment.', author: 'Jim Rohn' },
    { text: 'Either you run the day, or the day runs you.', author: 'Jim Rohn' },
    { text: 'Motivation is what gets you started. Habit is what keeps you going.', author: 'Jim Rohn' },
    { text: 'We generate fears while we sit. We overcome them by action.', author: 'Dr. Henry Link' },
    { text: 'The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.', author: 'Winston Churchill' },
    { text: 'A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.', author: 'Sir Winston Churchill' },
    { text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis' },
    { text: 'Hardships often prepare ordinary people for an extraordinary destiny.', author: 'C.S. Lewis' },
    { text: 'Friendship is born at that moment when one person says to another, \'What! You too?\'', author: 'C.S. Lewis' },
    { text: 'Courage is not simply one of the virtues, but the form of every virtue at the testing point.', author: 'C.S. Lewis' },
    { text: 'There is nothing either good or bad, but thinking makes it so.', author: 'William Shakespeare' },
    { text: 'We know what we are, but know not what we may be.', author: 'William Shakespeare' },
    { text: 'Our doubts are traitors, and make us lose the good we oft might win, by fearing to attempt.', author: 'William Shakespeare' },
    { text: 'Better three hours too soon than a minute too late.', author: 'William Shakespeare' },
    { text: 'Be not afraid of greatness: some are born great, some achieve greatness, and some have greatness thrust upon them.', author: 'William Shakespeare' },
    { text: 'To exist is to change, to change is to mature, to mature is to go on creating oneself endlessly.', author: 'Henri Bergson' },
    { text: 'The unexamined life is not worth living.', author: 'Socrates (attributed)' },
    { text: 'The only true wisdom is in knowing you know nothing.', author: 'Socrates (attributed)' },
    { text: 'Employ your time in improving yourself by other men\'s writings, so that you shall gain easily what others have labored hard for.', author: 'Socrates (attributed)' },
    { text: 'An honest man is always a child.', author: 'Socrates (attributed)' },
    { text: 'The greatest wealth is to live content with little.', author: 'Plato (attributed)' },
    { text: 'Human behavior flows from three main sources: desire, emotion, and knowledge.', author: 'Plato (attributed)' },
    { text: 'Be kind, for everyone you meet is fighting a harder battle.', author: 'Ian Maclaren (often misattributed to Plato)' },
    { text: 'At the touch of love, everyone becomes a poet.', author: 'Plato (attributed)' },
    { text: 'Excellence is never an accident. It is always the result of high intention, sincere effort, and intelligent execution.', author: 'Aristotle' },
    { text: 'Knowing yourself is the beginning of all wisdom.', author: 'Aristotle' },
    { text: 'The energy of the mind is the essence of life.', author: 'Aristotle' },
    { text: 'Pleasure in the job puts perfection in the work.', author: 'Aristotle' },
    { text: 'It is the mark of an educated mind to be able to entertain a thought without accepting it.', author: 'Aristotle' },
    { text: 'Waste no more time arguing about what a good man should be. Be one.', author: 'Marcus Aurelius' },
    { text: 'The impediment to action advances action. What stands in the way becomes the way.', author: 'Marcus Aurelius' },
    { text: 'How much trouble he avoids who does not look to see what his neighbor says or does.', author: 'Marcus Aurelius' },
    { text: 'Confine yourself to the present.', author: 'Marcus Aurelius' },
    { text: 'Very little is needed to make a happy life; it is all within yourself, in your way of thinking.', author: 'Marcus Aurelius' },
    { text: 'He who has overcome his fears will truly be free.', author: 'Aristotle' },
    { text: 'It is not length of life, but depth of life.', author: 'Ralph Waldo Emerson' },
    { text: 'The greatest glory in living lies not in never falling, but in rising every time we fall.', author: 'Nelson Mandela' },
    { text: 'There is no passion to be found playing small — in settling for a life that is less than the one you are capable of living.', author: 'Nelson Mandela' },
    { text: 'A winner is a dreamer who never gives up.', author: 'Nelson Mandela' },
    { text: 'Success usually comes to those who are too busy to be looking for it.', author: 'Henry David Thoreau' },
    { text: 'Go confidently in the direction of your dreams. Live the life you have imagined.', author: 'Henry David Thoreau' },
    { text: 'It\'s not what you look at that matters, it\'s what you see.', author: 'Henry David Thoreau' },
    { text: 'Things do not change; we change.', author: 'Henry David Thoreau' },
    { text: 'The mass of men lead lives of quiet desperation.', author: 'Henry David Thoreau' },
    { text: 'What lies before us and what lies behind us are small matters compared to what lies within us.', author: 'Henry David Thoreau' },
    { text: 'Happiness is not something readymade. It comes from your own actions.', author: 'Dalai Lama' },
    { text: 'Remember that not getting what you want is sometimes a wonderful stroke of luck.', author: 'Dalai Lama' },
    { text: 'Be kind whenever possible. It is always possible.', author: 'Dalai Lama' },
    { text: 'Just as ripples spread out when a single pebble is dropped into water, the actions of individuals can have far-reaching effects.', author: 'Dalai Lama' },
    { text: 'Choose to be optimistic, it feels better.', author: 'Dalai Lama' },
    { text: 'Peace comes from within. Do not seek it without.', author: 'Buddha (attributed)' },
    { text: 'The mind is everything. What you think you become.', author: 'Buddha (attributed)' },
    { text: 'Three things cannot be long hidden: the sun, the moon, and the truth.', author: 'Buddha (attributed)' },
    { text: 'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.', author: 'Buddha (attributed)' },
    { text: 'You yourself, as much as anybody in the entire universe, deserve your love and affection.', author: 'Buddha (attributed)' },
    { text: 'When I let go of what I am, I become what I might be.', author: 'Lao Tzu (attributed)' },
    { text: 'Simplicity, patience, compassion. These three are your greatest treasures.', author: 'Lao Tzu (attributed)' },
    { text: 'The world is won by those who let it go.', author: 'Lao Tzu (attributed)' },
    { text: 'Silence is a source of great strength.', author: 'Lao Tzu (attributed)' },
    { text: 'Push yourself, because no one else is going to do it for you.', author: 'Unknown' },
    { text: 'Great things never come from comfort zones.', author: 'Unknown' },
    { text: 'The distance between your dreams and reality is called action.', author: 'Unknown' },
    { text: 'Difficult roads often lead to beautiful destinations.', author: 'Unknown' },
    { text: 'Do the best you can until you know better. Then when you know better, do better.', author: 'Maya Angelou' },
    { text: 'There is no greater agony than bearing an untold story inside you.', author: 'Maya Angelou' },
    { text: 'You may not control all the events that happen to you, but you can decide not to be reduced by them.', author: 'Maya Angelou' },
    { text: 'My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style.', author: 'Maya Angelou' },
    { text: 'History, despite its wrenching pain, cannot be unlived, but if faced with courage, need not be lived again.', author: 'Maya Angelou' },
    { text: 'When you replace \'why is this happening to me\' with \'what is this trying to teach me?\' — everything shifts.', author: 'Eckhart Tolle' },
    { text: 'Realize deeply that the present moment is all you ever have.', author: 'Eckhart Tolle' },
    { text: 'Awareness is the greatest agent for change.', author: 'Eckhart Tolle' },
    { text: 'The primary cause of unhappiness is never the situation but your thoughts about it.', author: 'Eckhart Tolle' },
    { text: 'You find peace not by rearranging the circumstances of your life, but by realizing who you are at the deepest level.', author: 'Eckhart Tolle' },
    { text: 'In order to write about life, first you must live it.', author: 'Ernest Hemingway' },
    { text: 'Courage is grace under pressure.', author: 'Ernest Hemingway' },
    { text: 'The world breaks everyone, and afterward, some are strong at the broken places.', author: 'Ernest Hemingway' },
    { text: 'Never confuse motion with action.', author: 'Ernest Hemingway' },
    { text: 'There is nothing to writing. All you do is sit down at a typewriter and bleed.', author: 'Ernest Hemingway' },
    { text: 'Not all those who wander are lost.', author: 'J.R.R. Tolkien' },
    { text: 'All we have to decide is what to do with the time that is given us.', author: 'J.R.R. Tolkien' },
    { text: 'Even the smallest person can change the course of the future.', author: 'J.R.R. Tolkien' },
    { text: 'It\'s the job that\'s never started as takes longest to finish.', author: 'J.R.R. Tolkien' },
    { text: 'Some believe it is only great power that can hold evil in check, but that is not what I have found. I have found that it is the small everyday deeds of ordinary folk that keep the darkness at bay.', author: 'J.R.R. Tolkien' },
    { text: 'It does not do to dwell on dreams and forget to live.', author: 'J.K. Rowling' },
    { text: 'It is our choices that show what we truly are, far more than our abilities.', author: 'J.K. Rowling' },
    { text: 'Rock bottom became the solid foundation on which I rebuilt my life.', author: 'J.K. Rowling' },
    { text: 'We do not need magic to transform our world. We carry all the power we need inside ourselves already.', author: 'J.K. Rowling' },
    { text: 'Happiness can be found even in the darkest of times, if one only remembers to turn on the light.', author: 'J.K. Rowling' },
    { text: 'You are never too old to set another goal or dream a new dream.', author: 'Les Brown' },
    { text: 'It\'s possible for ordinary people to choose to be extraordinary.', author: 'Elon Musk' },
    { text: 'When something is important enough, you do it even if the odds are not in your favor.', author: 'Elon Musk' },
    { text: 'I think it\'s very important to have a feedback loop, where you\'re constantly thinking about what you\'ve done and how you could be doing it better.', author: 'Elon Musk' },
    { text: 'Persistence is very important. You should not give up unless you are forced to give up.', author: 'Elon Musk' },
    { text: 'Failure is an option here. If things are not failing, you are not innovating enough.', author: 'Elon Musk' },
    { text: 'Your most unhappy customers are your greatest source of learning.', author: 'Bill Gates' },
    { text: 'It\'s fine to celebrate success, but it is more important to heed the lessons of failure.', author: 'Bill Gates' },
    { text: 'Success is a lousy teacher. It seduces smart people into thinking they can\'t lose.', author: 'Bill Gates' },
    { text: 'As we look ahead into the next century, leaders will be those who empower others.', author: 'Bill Gates' },
    { text: 'Don\'t compare yourself with anyone in this world. If you do so, you are insulting yourself.', author: 'Bill Gates' },
    { text: 'If you are not embarrassed by the first version of your product, you\'ve launched too late.', author: 'Reid Hoffman' },
    { text: 'Ideas are easy. Implementation is hard.', author: 'Guy Kawasaki' },
    { text: 'The best way to predict the future is to invent it.', author: 'Alan Kay' },
    { text: 'Innovation distinguishes between a leader and a follower.', author: 'Steve Jobs' },
    { text: 'Design is not just what it looks like and feels like. Design is how it works.', author: 'Steve Jobs' },
    { text: 'Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.', author: 'Steve Jobs' },
    { text: 'I\'m convinced that about half of what separates successful entrepreneurs from the non-successful ones is pure perseverance.', author: 'Steve Jobs' },
    { text: 'Have the courage to follow your heart and intuition. They somehow already know what you truly want to become.', author: 'Steve Jobs' },
    { text: 'There is no substitute for hard work.', author: 'Thomas Edison' },
    { text: 'Opportunity is missed by most people because it is dressed in overalls and looks like work.', author: 'Thomas Edison' },
    { text: 'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.', author: 'Thomas Edison' },
    { text: 'Show up, show up, show up, and after a while the muse shows up too.', author: 'Isabel Allende' },
    { text: 'Write what disturbs you, what you fear, what you have not been willing to speak about.', author: 'Isabel Allende' },
    { text: 'You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.', author: 'Dr. Seuss' },
    { text: 'Don\'t cry because it\'s over, smile because it happened.', author: 'Dr. Seuss' },
    { text: 'Sometimes the questions are complicated and the answers are simple.', author: 'Dr. Seuss' },
    { text: 'Why fit in when you were born to stand out?', author: 'Dr. Seuss' },
    { text: 'The more that you read, the more things you will know. The more that you learn, the more places you\'ll go.', author: 'Dr. Seuss' },
    { text: 'Grant me the serenity to accept the things I cannot change, courage to change the things I can, and wisdom to know the difference.', author: 'Reinhold Niebuhr' },
    { text: 'The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.', author: 'Helen Keller' },
    { text: 'Although the world is full of suffering, it is also full of the overcoming of it.', author: 'Helen Keller' },
    { text: 'Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.', author: 'Helen Keller' },
    { text: 'Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened.', author: 'Helen Keller' },
    { text: 'When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.', author: 'Helen Keller' },
    { text: 'It is during our darkest moments that we must focus to see the light — and keep walking anyway.', author: 'Helen Keller (adapted)' },
    { text: 'I long to accomplish a great and noble task, but it is my chief duty to accomplish small tasks as if they were great and noble.', author: 'Helen Keller' },
    { text: 'The best way out is always through.', author: 'Robert Frost' },
    { text: 'In three words I can sum up everything I\'ve learned about life: it goes on — and so do you.', author: 'Robert Frost (adapted)' },
    { text: 'Nothing in life is to be feared, it is only to be understood.', author: 'Marie Curie' },
    { text: 'I was taught that the way of progress was neither swift nor easy.', author: 'Marie Curie' },
    { text: 'One never notices what has been done; one can only see what remains to be done.', author: 'Marie Curie' },
    { text: 'Be less curious about people and more curious about ideas.', author: 'Marie Curie' },
    { text: 'Life is not easy for any of us. But what of that? We must have perseverance and above all confidence in ourselves.', author: 'Marie Curie' },
    { text: 'You must do the things you think you cannot do.', author: 'Eleanor Roosevelt' },
    { text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt' },
    { text: 'No one can make you feel inferior without your consent.', author: 'Eleanor Roosevelt' },
    { text: 'Great minds discuss ideas; average minds discuss events; small minds discuss people.', author: 'Eleanor Roosevelt' },
    { text: 'It takes as much energy to wish as it does to plan.', author: 'Eleanor Roosevelt' },
    { text: 'Do one thing every day that scares you.', author: 'Eleanor Roosevelt' },
    { text: 'Yesterday is history, tomorrow is a mystery, today is a gift, that\'s why it\'s called the present.', author: 'Alice Morse Earle' },
    { text: 'The only limit to our realization of tomorrow will be our doubts of today.', author: 'Franklin D. Roosevelt' },
    { text: 'Happiness lies in the joy of achievement and the thrill of creative effort.', author: 'Franklin D. Roosevelt' },
    { text: 'The only thing we have to fear is fear itself.', author: 'Franklin D. Roosevelt' },
    { text: 'When you reach the end of your rope, tie a knot in it and hang on.', author: 'Franklin D. Roosevelt (attributed)' },
    { text: 'Success is not measured by what you accomplish, but by the opposition you have encountered and the courage with which you have maintained the struggle.', author: 'Orison Swett Marden' },
    { text: 'I attribute my success to this: I never gave or took any excuse.', author: 'Florence Nightingale' },
    { text: 'How very little can be done under the spirit of fear.', author: 'Florence Nightingale' },
    { text: 'Let us never negotiate out of fear. But let us never fear to negotiate.', author: 'John F. Kennedy' },
    { text: 'Ask not what your country can do for you — ask what you can do for your country.', author: 'John F. Kennedy' },
    { text: 'Change is the law of life. And those who look only to the past or present are certain to miss the future.', author: 'John F. Kennedy' },
    { text: 'Efforts and courage are not enough without purpose and direction.', author: 'John F. Kennedy' },
    { text: 'We choose to go to the moon not because it is easy, but because it is hard.', author: 'John F. Kennedy' },
    { text: 'One person can make a difference, and everyone should try.', author: 'John F. Kennedy' },
    { text: 'The greatest discovery of my generation is that a human being can alter his life by altering his attitudes.', author: 'William James' },
    { text: 'Act as if what you do makes a difference. It does.', author: 'William James' },
    { text: 'The art of being wise is knowing what to overlook.', author: 'William James' },
    { text: 'Nothing is so fatiguing as the eternal hanging on of an uncompleted task.', author: 'William James' },
    { text: 'Whenever you are confronted with an opponent, conquer him with love.', author: 'Mahatma Gandhi' },
    { text: 'You must be the change you wish to see in the world.', author: 'Mahatma Gandhi (attributed)' },
    { text: 'First they ignore you, then they laugh at you, then they fight you, then you win.', author: 'Mahatma Gandhi (attributed)' },
    { text: 'A man is but the product of his thoughts. What he thinks, he becomes.', author: 'Mahatma Gandhi (attributed)' },
    { text: 'Strength does not come from physical capacity. It comes from an indomitable will.', author: 'Mahatma Gandhi' },
    { text: 'Live as if you were to die tomorrow. Learn as if you were to live forever.', author: 'Mahatma Gandhi (attributed)' },
    { text: 'The weak can never forgive. Forgiveness is the attribute of the strong.', author: 'Mahatma Gandhi' },
    { text: 'Freedom is not worth having if it does not include the freedom to make mistakes.', author: 'Mahatma Gandhi' },
    { text: 'In a gentle way, you can shake the world.', author: 'Mahatma Gandhi' },
    { text: 'Happiness is when what you think, what you say, and what you do are in harmony.', author: 'Mahatma Gandhi (attributed)' },
    { text: 'It\'s not the load that breaks you down, it\'s the way you carry it.', author: 'Lou Holtz' },
    { text: 'Nobody who ever gave his best regretted it.', author: 'George Halas' },
    { text: 'It\'s hard to beat a person who never gives up.', author: 'Babe Ruth' },
    { text: 'Every strike brings me closer to the next home run.', author: 'Babe Ruth' },
    { text: 'Yesterday\'s home runs don\'t win today\'s games.', author: 'Babe Ruth' },
    { text: 'Never let the fear of striking out keep you from playing the game.', author: 'Babe Ruth' },
    { text: 'The way a team plays as a whole determines its success. You may have the greatest bunch of individual stars, but if they don\'t play together, the club won\'t be worth a dime.', author: 'Babe Ruth' },
    { text: 'Age is no barrier. It\'s a limitation you put on your mind.', author: 'Jackie Joyner-Kersee' },
    { text: 'Ability may get you to the top, but it takes character to keep you there.', author: 'Zig Ziglar' },
    { text: 'There may be people that have more talent than you, but there\'s no excuse for anyone to work harder than you do.', author: 'Derek Jeter' },
    { text: 'It\'s not whether you get knocked down; it\'s whether you get back up that counts.', author: 'Vince Lombardi' },
    { text: 'You can\'t put a limit on anything. The more you dream, the farther you get.', author: 'Michael Phelps' },
    { text: 'A champion is defined not by their wins but by how they can recover when they fall.', author: 'Serena Williams' },
    { text: 'The success of every woman should be the inspiration to another. We should raise each other up.', author: 'Serena Williams' },
    { text: 'Tennis just a physical chess game. The mentality is very tough.', author: 'Serena Williams' },
    { text: 'I really think a champion is defined not by their wins but by how they can recover when they fall.', author: 'Serena Williams' },
    { text: 'It\'s not about perfect. It\'s about effort.', author: 'Jillian Michaels' },
    { text: 'You are never too old to bounce back.', author: 'Kobe Bryant' },
    { text: 'Everything negative — pressure, challenges — is all an opportunity for me to rise.', author: 'Kobe Bryant' },
    { text: 'The most important thing is to try and inspire people so that they can be great in whatever they want to do.', author: 'Kobe Bryant' },
    { text: 'I can\'t relate to lazy people. We don\'t speak the same language.', author: 'Kobe Bryant' },
    { text: 'Rest at the end, not in the middle.', author: 'Kobe Bryant' },
    { text: 'If you\'re afraid of failure, you don\'t deserve to be successful.', author: 'Charles Barkley' },
    { text: 'I\'ve failed over and over and over again in my life, and that is why I succeed.', author: 'Michael Jordan' },
    { text: 'Do not let what you cannot do interfere with what you can do.', author: 'John Wooden' },
    { text: 'Be quick, but don\'t hurry.', author: 'John Wooden' },
    { text: 'It\'s what you learn after you know it all that counts.', author: 'John Wooden' },
    { text: 'Failing to prepare is preparing to fail.', author: 'John Wooden' },
    { text: 'You can\'t let praise or criticism get to you. It\'s a weakness to get caught up in either one.', author: 'John Wooden' },
    { text: 'Success is peace of mind, which is a direct result of self-satisfaction in knowing you made the effort to become the best of which you\'re capable.', author: 'John Wooden' },
    { text: 'If you don\'t have confidence, you\'ll always find a way not to win.', author: 'Carl Lewis' },
    { text: 'I hated every minute of training, but I said, don\'t quit. Suffer now and live the rest of your life as a champion.', author: 'Muhammad Ali' },
    { text: 'It\'s not about how hard you hit. It\'s about how hard you can get hit and keep moving forward.', author: 'Sylvester Stallone' },
    { text: 'Every champion was once a contender that refused to give up.', author: 'Rocky Balboa (film)' },
    { text: 'A goal is not always meant to be reached, it often serves simply as something to aim at.', author: 'Bruce Lee' },
    { text: 'Notice that the stiffest tree is most easily cracked, while the bamboo survives by bending with the wind.', author: 'Bruce Lee' },
    { text: 'As you think, so shall you become.', author: 'Bruce Lee (attributed)' },
    { text: 'Do not pray for an easy life, pray for the strength to endure a difficult one.', author: 'Bruce Lee (attributed)' },
    { text: 'Absorb what is useful, discard what is not, add what is uniquely your own.', author: 'Bruce Lee' },
    { text: 'Simplicity is the ultimate sophistication.', author: 'Leonardo da Vinci' },
    { text: 'Learning never exhausts the mind.', author: 'Leonardo da Vinci' },
    { text: 'Art is never finished, only abandoned.', author: 'Leonardo da Vinci' },
    { text: 'Iron rusts from disuse; stagnant water loses its purity. So does inaction sap the vigor of the mind.', author: 'Leonardo da Vinci' },
    { text: 'It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them.', author: 'Leonardo da Vinci' },
    { text: 'Where the willingness is great, the difficulties cannot be great.', author: 'Niccolo Machiavelli' },
    { text: 'Never waste an opportunity created by a good crisis.', author: 'Niccolo Machiavelli' },
    { text: 'Do not go gentle into that good night. Rage, rage against the dying of the light.', author: 'Dylan Thomas' },
    { text: 'Poetry is when an emotion has found its thought and the thought has found words.', author: 'Robert Frost' },
    { text: 'I have been bent and broken, but — I hope — into a better shape.', author: 'Charles Dickens' },
    { text: 'No one is useless in this world who lightens the burdens of another.', author: 'Charles Dickens' },
    { text: 'Reflect upon your present blessings, of which every man has many.', author: 'Charles Dickens' },
    { text: 'It was the best of times, it was the worst of times.', author: 'Charles Dickens' },
    { text: 'There is a wisdom of the head, and a wisdom of the heart.', author: 'Charles Dickens' },
    { text: 'The only way to make sense out of change is to plunge into it, move with it, and join the dance.', author: 'Alan Watts' },
    { text: 'You are an aperture through which the universe is looking at and exploring itself.', author: 'Alan Watts' },
    { text: 'This is the real secret of life — to be completely engaged with what you are doing in the here and now.', author: 'Alan Watts' },
    { text: 'Trying to define yourself is like trying to bite your own teeth.', author: 'Alan Watts' },
    { text: 'Muddy water is best cleared by leaving it alone.', author: 'Alan Watts' },
    { text: 'I am not a product of my circumstances. I am a product of my decisions.', author: 'Stephen Covey' },
    { text: 'Begin with the end in mind.', author: 'Stephen Covey' },
    { text: 'Most of us spend too much time on what is urgent and not enough time on what is important.', author: 'Stephen Covey' },
    { text: 'The key is not to prioritize what\'s on your schedule, but to schedule your priorities.', author: 'Stephen Covey' },
    { text: 'Trust is the glue of life. It\'s the most essential ingredient in effective communication.', author: 'Stephen Covey' },
    { text: 'Seek first to understand, then to be understood.', author: 'Stephen Covey' },
    { text: 'When we are no longer able to change a situation, we are challenged to change ourselves.', author: 'Viktor Frankl' },
    { text: 'Everything can be taken from a man but one thing: the last of the human freedoms — to choose one\'s attitude in any given set of circumstances.', author: 'Viktor Frankl' },
    { text: 'Those who have a \'why\' to live, can bear with almost any \'how\'.', author: 'Viktor Frankl' },
    { text: 'What is to give light must endure burning.', author: 'Viktor Frankl' },
    { text: 'Live as if you were living already for the second time and as if you had acted the first time as wrongly as you are about to act now.', author: 'Viktor Frankl' },
    { text: 'The pursuit of happiness is not the answer. Happiness ensues from a life lived in service of a cause greater than oneself.', author: 'Viktor Frankl (adapted)' },
    { text: 'In some ways suffering ceases to be suffering at the moment it finds a meaning.', author: 'Viktor Frankl' },
    { text: 'The most beautiful people we have known are those who have known defeat, known suffering, known struggle, known loss, and have found their way out of the depths.', author: 'Elisabeth Kubler-Ross' },
    { text: 'People are like stained-glass windows: they sparkle and shine when the sun is out, but when the darkness sets in, their true beauty is revealed only if there is a light from within.', author: 'Elisabeth Kubler-Ross' },
    { text: 'The very act of trying to be happy contributes largely to unhappiness.', author: 'Eric Hoffer' },
    { text: 'In times of change, learners inherit the earth, while the learned find themselves beautifully equipped to deal with a world that no longer exists.', author: 'Eric Hoffer' },
    { text: 'The hardest arithmetic to master is that which enables us to count our blessings.', author: 'Eric Hoffer' },
    { text: 'Freedom is not the absence of commitments, but the ability to choose what I commit myself to.', author: 'Paulo Coelho' },
    { text: 'When you want something, all the universe conspires in helping you to achieve it.', author: 'Paulo Coelho' },
    { text: 'The secret of life, though, is to fall seven times and to get up eight times.', author: 'Paulo Coelho' },
    { text: 'It\'s the possibility of having a dream come true that makes life interesting.', author: 'Paulo Coelho' },
    { text: 'One only needs the courage to accept the challenges each day sends our way.', author: 'Paulo Coelho' },
    { text: 'There are years that ask questions and years that answer.', author: 'Zora Neale Hurston' },
    { text: 'Research is formalized curiosity. It is poking and prying with a purpose.', author: 'Zora Neale Hurston' },
    { text: 'If you are silent about your pain, they\'ll kill you and say you enjoyed it.', author: 'Zora Neale Hurston' },
    { text: 'Not all storms come to disrupt your life, some come to clear your path.', author: 'Unknown' },
    { text: 'You didn\'t come this far to only come this far.', author: 'Unknown' },
    { text: 'Discipline is choosing between what you want now and what you want most.', author: 'Abraham Lincoln (attributed)' },
    { text: 'Character is doing the right thing when nobody\'s looking.', author: 'J.C. Watts' },
    { text: 'Leadership is the capacity to translate vision into reality.', author: 'Warren Bennis' },
    { text: 'The function of leadership is to produce more leaders, not more followers.', author: 'Ralph Nader' },
    { text: 'Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others.', author: 'Jack Welch' },
    { text: 'Management is doing things right; leadership is doing the right things.', author: 'Peter Drucker' },
    { text: 'The best executive is the one who has sense enough to pick good people to do what he wants done, and self-restraint enough to keep from meddling with them while they do it.', author: 'Theodore Roosevelt' },
    { text: 'A leader is one who knows the way, goes the way, and shows the way.', author: 'John C. Maxwell' },
    { text: 'People buy into the leader before they buy into the vision.', author: 'John C. Maxwell' },
    { text: 'The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things.', author: 'Ronald Reagan' },
    { text: 'Leaders think and talk about the solutions. Followers think and talk about the problems.', author: 'Brian Tracy' },
    { text: 'Do not wait for leaders; do it alone, person to person.', author: 'Mother Teresa' },
    { text: 'If you can\'t feed a hundred people, then feed just one.', author: 'Mother Teresa' },
    { text: 'Not all of us can do great things, but we can do small things with great love.', author: 'Mother Teresa' },
    { text: 'Spread love everywhere you go. Let no one ever come to you without leaving happier.', author: 'Mother Teresa' },
    { text: 'Peace begins with a smile.', author: 'Mother Teresa' },
    { text: 'I know God will not give me anything I can\'t handle. I just wish that He didn\'t trust me so much.', author: 'Mother Teresa' },
    { text: 'Kindness is a language which the deaf can hear and the blind can see.', author: 'Mark Twain' },
    { text: 'The two most important days in your life are the day you are born and the day you find out why you were born.', author: 'Mark Twain (adapted)' },
    { text: 'Whenever you find yourself on the side of the majority, it is time to pause and reflect.', author: 'Mark Twain' },
    { text: 'Kindness is the language which the deaf can hear and the blind can see.', author: 'Mark Twain' },
    { text: 'There are two great days in a person\'s life — the day we are born and the day we discover why.', author: 'William Barclay' },
    { text: 'Don\'t judge each day by the harvest you reap but by the seeds that you plant.', author: 'Robert Louis Stevenson' },
    { text: 'To be what we are, and to become what we are capable of becoming, is the only end of life.', author: 'Robert Louis Stevenson' },
    { text: 'Everyone lives by selling something.', author: 'Robert Louis Stevenson' },
    { text: 'Keep your face always toward the sunshine, and shadows will fall behind you.', author: 'Walt Whitman' },
    { text: 'Be curious, not judgmental.', author: 'Walt Whitman' },
    { text: 'Re-examine all that you have been told. Dismiss what insults your soul.', author: 'Walt Whitman' },
    { text: 'I exist as I am, that is enough.', author: 'Walt Whitman' },
    { text: 'Nothing can bring you peace but yourself.', author: 'Ralph Waldo Emerson' },
    { text: 'Adopt the pace of nature: her secret is patience.', author: 'Ralph Waldo Emerson' },
    { text: 'Write it on your heart that every day is the best day in the year.', author: 'Ralph Waldo Emerson' },
    { text: 'Every wall is a door.', author: 'Ralph Waldo Emerson' },
    { text: 'The only way to have a friend is to be one.', author: 'Ralph Waldo Emerson' },
    { text: 'What you do speaks so loudly that I cannot hear what you say.', author: 'Ralph Waldo Emerson' },
    { text: 'Guard well your spare moments. They are like uncut diamonds.', author: 'Ralph Waldo Emerson' },
    { text: 'It is not the mountain we conquer, but ourselves.', author: 'Sir Edmund Hillary' },
    { text: 'Nothing is impossible, the word itself says \'I\'m possible\'!', author: 'Audrey Hepburn' },
    { text: 'The most important thing is to enjoy your life, to be happy — it\'s all that matters.', author: 'Audrey Hepburn' },
    { text: 'For beautiful eyes, look for the good in others.', author: 'Audrey Hepburn' },
    { text: 'As you grow older, you will discover that you have two hands — one for helping yourself, the other for helping others.', author: 'Audrey Hepburn' },
    { text: 'I believe in pink. I believe that laughing is the best calorie burner.', author: 'Audrey Hepburn' },
    { text: 'Do what you feel in your heart to be right — for you\'ll be criticized anyway.', author: 'Eleanor Roosevelt' },
    { text: 'The purpose of our lives is to be happy.', author: 'Dalai Lama' },
    { text: 'Life is really simple, but we insist on making it complicated.', author: 'Confucius (attributed)' },
    { text: 'By three methods we may learn wisdom: first, by reflection, which is noblest; second, by imitation, which is easiest; and third by experience, which is the bitterest.', author: 'Confucius (attributed)' },
    { text: 'Choose a job you love, and you will never have to work a day in your life.', author: 'Confucius (attributed)' },
    { text: 'When it is obvious that the goals cannot be reached, don\'t adjust the goals, adjust the action steps.', author: 'Confucius (attributed)' },
    { text: 'Everything has beauty, but not everyone sees it.', author: 'Confucius (attributed)' },
    { text: 'Life\'s most persistent and urgent question is: What are you doing for others?', author: 'Martin Luther King Jr.' },
    { text: 'A genuine leader is not a searcher for consensus but a molder of consensus.', author: 'Martin Luther King Jr.' },
    { text: 'We must accept finite disappointment, but never lose infinite hope.', author: 'Martin Luther King Jr.' },
    { text: 'The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy.', author: 'Martin Luther King Jr.' },
    { text: 'Injustice anywhere is a threat to justice everywhere.', author: 'Martin Luther King Jr.' },
    { text: 'Only in the darkness can you see the stars.', author: 'Martin Luther King Jr.' },
    { text: 'Change will not come if we wait for some other person or some other time. We are the ones we\'ve been waiting for.', author: 'Barack Obama' },
    { text: 'The best way to not feel hopeless is to get up and do something.', author: 'Barack Obama' },
    { text: 'Yes we can.', author: 'Barack Obama' },
    { text: 'We need not think alike to love alike.', author: 'Barack Obama (adapted)' },
    { text: 'If you\'re walking down the right path and you\'re willing to keep walking, eventually you\'ll make progress.', author: 'Barack Obama' },
    { text: 'There is not a black America and a white America — there\'s the United States of America.', author: 'Barack Obama' },
    { text: 'We may encounter many defeats but we must not be defeated.', author: 'Maya Angelou' },
    { text: 'The greatest legacy one can pass on to one\'s children and grandchildren is not money or other material things, but rather a legacy of character.', author: 'Billy Graham' },
    { text: 'Life is like a piano — the white keys represent happiness and the black keys represent sadness. As you go through life\'s journey, remember that the black keys also make music.', author: 'Unknown' },
    { text: 'The soul becomes dyed with the color of its thoughts.', author: 'Marcus Aurelius' },
    { text: 'If it is not right, do not do it. If it is not true, do not say it.', author: 'Marcus Aurelius' },
    { text: 'Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.', author: 'Marcus Aurelius' },
    { text: 'You could leave life right now. Let that determine what you do and say and think.', author: 'Marcus Aurelius' },
    { text: 'Dwell on the beauty of life. Watch the stars, and see yourself running with them.', author: 'Marcus Aurelius' },
    { text: 'It is not death that a man should fear, but he should fear never beginning to live.', author: 'Marcus Aurelius' },
    { text: 'Never regard something as being to your advantage if it makes you break your word or lose your self-respect.', author: 'Marcus Aurelius' },
    { text: 'Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.', author: 'Marcus Aurelius' },
    { text: 'The best revenge is to be unlike him who performed the injury.', author: 'Marcus Aurelius' }
  ],

  focus: [
    { text: "Almost everything will work again if you unplug it for a few minutes, including you.", author: "Anne Lamott" },
    { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
    { text: "Where attention goes, energy flows.", author: "James Redfield" },
    { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle (attributed)" },
    { text: "My mind is never clearer than when I am looking at something far away.", author: "Mary Oliver" },
    { text: "The quieter you become, the more you can hear.", author: "Ram Dass" }
  ],

  tension: [
    { text: "Tension is who you think you should be. Relaxation is who you are.", author: "Chinese Proverb" },
    { text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James" },
    { text: "Your mind will answer most questions if you learn to relax and wait for the answer.", author: "William S. Burroughs" },
    { text: "Within you, there is a stillness and a sanctuary to which you can retreat at any time.", author: "Hermann Hesse" },
    { text: "Stress is caused by being 'here' but wanting to be 'there'.", author: "Eckhart Tolle" },
    { text: "The time to relax is when you don't have time for it.", author: "Sydney J. Harris" }
  ],

  movement: [
    { text: "Those who think they have no time for bodily exercise will sooner or later have to find time for illness.", author: "Edward Stanley" },
    { text: "Movement is a medicine for creating change in a person's physical, emotional, and mental states.", author: "Carol Welch" },
    { text: "A year from now you may wish you had started today. The same is true of standing up.", author: "Karen Lamb (adapted)" },
    { text: "Sitting is the new smoking.", author: "Dr. James Levine" },
    { text: "The body needs movement the way the mind needs novelty.", author: "Siri Hustvedt (adapted)" },
    { text: "Rest is not idleness, and to lie sometimes on the grass under trees on a summer's day, listening to the murmur of water, or watching the clouds float across the sky, is by no means a waste of time.", author: "John Lubbock" }
  ],

  calm: [
    { text: "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", author: "Thich Nhat Hanh" },
    { text: "Breath is the bridge which connects life to consciousness, which unites your body to your thoughts.", author: "Thich Nhat Hanh" },
    { text: "The restless mind is like a calm lake disturbed by a wind. The breath is the wind that can also calm it.", author: "B.K.S. Iyengar" },
    { text: "When you own your breath, nobody can steal your peace.", author: "David Foster Wallace (attributed)" },
    { text: "The meaning of life is just to be alive. It is so plain and so obvious and so simple. And yet, everybody rushes around as if it were necessary to achieve something beyond that.", author: "Alan Watts" },
    { text: "Slow is smooth, and smooth is fast.", author: "Navy SEAL maxim" }
  ],

  posture: [
    { text: "The body holds the score. The way we carry ourselves tells the story of how we've been living.", author: "Bessel van der Kolk (adapted)" },
    { text: "Good posture is the foundation of good health. You cannot build a strong house on a weak frame.", author: "Joseph Pilates (attributed)" },
    { text: "How you stand is how you walk. How you walk is how you think. How you think is how you live.", author: "Ido Portal (attributed)" },
    {   text: "The spine is the body's axis of integrity.", author: "F.M. Alexander" },
    { text: "You are as young as your spine is flexible.", author: "Joseph Pilates" },
    { text: "The body speaks even when the mouth is silent.", author: "Martha Graham (adapted)" }
  ],

  general: [
    { text: "Rest is not the enemy of ambition. It is its foundation.", author: "Shawn Achor (adapted)" },
    { text: "You do not rise to the level of your goals. You fall to the level of your systems.", author: "James Clear" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "What gets measured gets managed.", author: "Peter Drucker (attributed)" },
    { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Will Durant (often attributed to Aristotle)" },
    { text: "The obstacle is the path.", author: "Marcus Aurelius (attributed)" },
    { text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca" },
    { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
    { text: "He who has a why to live for can bear almost any how.", author: "Friedrich Nietzsche" },
    { text: "The wound is the place where the Light enters you.", author: "Rumi (attributed)" },
    { text: "Between stimulus and response there is a space. In that space is our power to choose our response.", author: "Viktor Frankl (attributed)" },
    { text: "Sometimes the most productive thing you can do is rest.", author: "Mark Black" }
  ],

  // Uplifting, encouraging verses only — rest, strength, peace. No judgment
  // or fear-themed passages. King James Version (public domain).
  faith: [
    { text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.", author: "Matthew 11:28, KJV" },
    { text: "Be still, and know that I am God.", author: "Psalm 46:10, KJV" },
    { text: "They that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.", author: "Isaiah 40:31, KJV" },
    { text: "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.", author: "Philippians 4:7, KJV" },
    { text: "I can do all things through Christ which strengtheneth me.", author: "Philippians 4:13, KJV" },
    { text: "A merry heart doeth good like a medicine: but a broken spirit drieth the bones.", author: "Proverbs 17:22, KJV" }
  ]
};

// Spreads a smaller list evenly across a larger one, proportional to their
// sizes, instead of concatenating them (which clusters the smaller list into
// one unbroken run — e.g. 6 faith quotes tacked onto the end of a large pool
// would show up as one long unbroken run at the end of the cycle, not a
// genuine blend). Works correctly regardless of how many quotes end up in
// either pool.
function interleaveProportional(major, minor) {
  const total = major.length + minor.length;
  const result = [];
  let mi = 0, ni = 0;
  for (let i = 0; i < total; i++) {
    const minorDueByNow = Math.floor((i + 1) * minor.length / total);
    if (ni < minorDueByNow) result.push(minor[ni++]);
    else result.push(major[mi++]);
  }
  return result;
}

// Builds the single unified quote pool used everywhere in the app: the new
// daily(488) famous-figure quotes plus every original category-specific and
// general quote, kept as extra variety rather than replaced. Each entry
// carries its source category + index so audio playback (quoteSrc) can still
// resolve the right pre-recorded file — nothing about how audio is looked up
// changes, only which quote shows on a given day and where it's shown.
let _unifiedPoolCache = null;
function buildUnifiedPool() {
  if (_unifiedPoolCache) return _unifiedPoolCache;
  const categories = ['daily', 'focus', 'tension', 'movement', 'calm', 'posture', 'general'];
  const major = [];
  categories.forEach(category => {
    QUOTES[category].forEach((q, index) => {
      major.push({ text: q.text, author: q.author, category, index });
    });
  });
  const minor = QUOTES.faith.map((q, index) => ({ text: q.text, author: q.author, category: 'faith', index }));
  _unifiedPoolCache = interleaveProportional(major, minor);
  return _unifiedPoolCache;
}

// The single daily quote — used by the dashboard hero card and the once-daily
// splash. Deterministic per day so both surfaces agree, and so it doesn't
// change if the dashboard re-renders.
function getMorningQuote(dayIndex) {
  const combined = buildUnifiedPool();
  return combined[dayIndex % combined.length];
}

// The after-break closing quote — a genuinely random pick from the same
// pool, independent of break topic, so completing several breaks in one day
// doesn't repeat the dashboard's quote-of-the-day or each other. This module
// has no storage of its own, so the caller (app.js) tracks which quotes have
// already been shown today and passes their "category-index" keys in to
// exclude; falls back to the full pool if everything's somehow been excluded.
function getRandomClosingQuote(excludeKeys) {
  const pool = buildUnifiedPool();
  const exclude = new Set(excludeKeys || []);
  const candidates = pool.filter(q => !exclude.has(`${q.category}-${q.index}`));
  const usable = candidates.length ? candidates : pool;
  return usable[Math.floor(Math.random() * usable.length)];
}

// Helper: get all categories
function getQuoteCategories() {
  return Object.keys(QUOTES);
}

if (typeof window !== 'undefined') {
  window.QUOTES = QUOTES;
  window.getMorningQuote = getMorningQuote;
  window.getRandomClosingQuote = getRandomClosingQuote;
}
