#!/bin/bash
# update-audio-manifest.sh — regenerate audio-manifest.js from the MP3s in audio/
# Run this from the build folder every time you add or remove recording files:
#   ./update-audio-manifest.sh

cd "$(dirname "$0")"
mkdir -p audio/breaks audio/learning

{
  echo "// audio-manifest.js — list of pre-recorded audio files that exist in /audio"
  echo "// AUTO-GENERATED by update-audio-manifest.sh — do not edit by hand."
  echo "// Naming: audio/breaks/<breakId>-step<N>-<gender>.mp3"
  echo "//         audio/learning/<episodeId>-<gender>.mp3     (<gender> = female | male)"
  echo "window.AUDIO_MANIFEST = ["
  find audio -name "*.mp3" | sort | sed "s/^/  '/;s/$/',/"
  echo "];"
} > audio-manifest.js

COUNT=$(find audio -name "*.mp3" | wc -l | tr -d ' ')
echo "audio-manifest.js updated — $COUNT recording(s) listed."
