// words.js — "Today's Word" vocabulary library
// One advanced, executive-relevant word per day, played as the opening
// segment of Lunch Break Learning before that day's topic episode.
// 183 words, shuffled into a fixed non-alphabetical play order — a full
// rotation takes 183 days, so each word repeats twice within a year.

const WORDS = [
  { id: 'w52', word: 'Catalyst', definition: 'A person or thing that precipitates an event or change.', example: "The failed product launch became the catalyst for rethinking the whole roadmap." },
  { id: 'w16', word: 'Laconic', definition: 'Using very few words; concise to the point of terseness.', example: "His laconic email left no room for misinterpretation." },
  { id: 'w99', word: 'Elucidate', definition: 'To make something clear; to explain.', example: "One diagram elucidated the data flow better than three pages of documentation." },
  { id: 'w161', word: 'Irascible', definition: 'Easily made angry; hot-tempered.', example: "The irascible client mellowed considerably once the delivery dates were finally met." },
  { id: 'w137', word: 'Impeccable', definition: 'In accordance with the highest standards; flawless.', example: "His impeccable timing turned a routine update into the highlight of the earnings call." },
  { id: 'w182', word: 'Nefarious', definition: 'Wicked or criminal.', example: "The whistleblower exposed a nefarious billing scheme that had run for years." },
  { id: 'w146', word: 'Indelible', definition: 'Making marks that cannot be removed; unforgettable.', example: "That first client disaster left an indelible lesson about over-promising deadlines." },
  { id: 'w82', word: 'Dichotomy', definition: 'A division into two sharply contrasting parts.', example: "The classic dichotomy between speed and quality showed up in every sprint review." },
  { id: 'w13', word: 'Pertinacious', definition: 'Holding firmly to an opinion or course of action; stubbornly persistent.', example: "His pertinacious pursuit of the client finally paid off after a year." },
  { id: 'w35', word: 'Amenable', definition: 'Open and responsive to suggestion.', example: "He was amenable to restructuring the deal once he saw the revised numbers." },
  { id: 'w68', word: 'Copious', definition: 'Abundant; in large quantities.', example: "She took copious notes during the client call, which saved the follow-up meeting." },
  { id: 'w36', word: 'Anomaly', definition: 'Something that deviates from what is standard or expected.', example: "The spike in refunds turned out to be an anomaly, not a trend." },
  { id: 'w103', word: 'Enigmatic', definition: 'Difficult to interpret or understand; mysterious.', example: "The CEO stayed enigmatic about the acquisition until the papers were signed." },
  { id: 'w89', word: 'Dogmatic', definition: 'Inclined to lay down principles as incontrovertibly true.', example: "He was dogmatic about the process, even after it clearly stopped working." },
  { id: 'w96', word: 'Egregious', definition: 'Outstandingly bad; shocking.', example: "The pricing error was egregious enough to warrant a same-day public apology." },
  { id: 'w23', word: 'Astute', definition: 'Having an ability to accurately assess situations; shrewd.', example: "An astute observation about customer behavior reshaped the entire campaign." },
  { id: 'w14', word: 'Sagacious', definition: 'Having good judgment; wise.', example: "The board valued her sagacious counsel during the merger talks." },
  { id: 'w108', word: 'Euphemism', definition: 'A mild word substituted for one considered harsh or blunt.', example: "'Right-sizing' was the euphemism everyone in the room understood but no one said aloud." },
  { id: 'w90', word: 'Dubious', definition: 'Not to be relied upon; suspect.', example: "The vendor's growth numbers looked dubious the moment we asked for the source data." },
  { id: 'w131', word: 'Homogeneous', definition: 'Uniform in composition; all of the same kind.', example: "A homogeneous customer base made segmentation almost unnecessary at first." },
  { id: 'w56', word: 'Coalesce', definition: 'To come together to form a single group or whole.', example: "The scattered feedback slowly coalesced into three clear product priorities." },
  { id: 'w67', word: 'Convivial', definition: 'Friendly, lively, and enjoyable.', example: "The convivial atmosphere at the retreat got even the quiet engineers talking strategy." },
  { id: 'w156', word: 'Intrepid', definition: 'Fearless; adventurous.', example: "Their intrepid entry into an unproven market paid off two years later." },
  { id: 'w164', word: 'Latent', definition: 'Present but not yet developed or visible.', example: "The survey uncovered a latent demand for a feature nobody had asked for directly." },
  { id: 'w104', word: 'Epitome', definition: 'A perfect example of a particular quality or type.', example: "The onboarding flow became the epitome of what 'simple' should look like." },
  { id: 'w30', word: 'Sanguine', definition: 'Optimistic or positive, especially in a difficult situation.', example: "She remained sanguine about the quarter despite the early setbacks." },
  { id: 'w07', word: 'Equanimity', definition: 'Mental calmness and composure, especially in a difficult situation.', example: "She responded to the crisis with remarkable equanimity." },
  { id: 'w88', word: 'Doctrinaire', definition: 'Rigidly attached to a theory without regard for practical difficulties.', example: "A doctrinaire approach to the old playbook nearly cost them the new market." },
  { id: 'w71', word: 'Debilitate', definition: 'To weaken or make feeble.', example: "Constant context-switching can debilitate even the most focused team." },
  { id: 'w149', word: 'Innate', definition: 'Inborn; natural rather than learned.', example: "She had an innate sense for which features customers would actually use." },
  { id: 'w163', word: 'Kinetic', definition: 'Relating to or resulting from motion; full of energy.', example: "The new office layout felt kinetic compared to the old row of quiet cubicles." },
  { id: 'w129', word: 'Heuristic', definition: 'A practical approach to problem-solving using experience-based shortcuts.', example: "The 'ship small, ship often' heuristic guided every product decision that quarter." },
  { id: 'w64', word: 'Consolidate', definition: 'To combine into a single, more effective whole.', example: "They consolidated four regional tools into one shared platform this year." },
  { id: 'w54', word: 'Chicanery', definition: 'The use of trickery to achieve a purpose.', example: "The audit turned up no chicanery, just a genuinely confusing invoicing system." },
  { id: 'w20', word: 'Judicious', definition: 'Having, showing, or done with good judgment or sense.', example: "A judicious use of resources kept the project under budget." },
  { id: 'w178', word: 'Morose', definition: 'Sullen and ill-tempered.', example: "He went morose for a week after the deal fell through at the last stage." },
  { id: 'w143', word: 'Incisive', definition: 'Sharply intelligent and direct.', example: "One incisive question from the CFO exposed the whole plan's weak assumption." },
  { id: 'w124', word: 'Gratuitous', definition: 'Uncalled for; lacking good reason.', example: "The gratuitous redesign added complexity without solving any real user problem." },
  { id: 'w98', word: 'Eloquent', definition: 'Fluent and persuasive in speaking or writing.', example: "Her eloquent closing argument turned a skeptical room into a room of buyers." },
  { id: 'w112', word: 'Expedient', definition: 'Convenient and practical, though possibly improper.', example: "It was expedient to skip the review, but it cost them a week of rework later." },
  { id: 'w87', word: 'Divergent', definition: 'Tending to develop in different directions.', example: "The two founders had divergent visions for the product's next stage." },
  { id: 'w80', word: 'Desultory', definition: 'Lacking a plan or purpose; disconnected.', example: "The desultory brainstorm produced a dozen ideas and no real direction." },
  { id: 'w179', word: 'Multifaceted', definition: 'Having many different aspects or sides.', example: "The pricing problem was more multifaceted than anyone realized until the data came in." },
  { id: 'w168', word: 'Litigious', definition: 'Prone to taking legal action.', example: "The market they entered was famously litigious over even minor trademark overlaps." },
  { id: 'w15', word: 'Fortuitous', definition: 'Happening by chance, especially a happy or beneficial one.', example: "A fortuitous introduction at the conference led to their biggest client." },
  { id: 'w70', word: 'Debacle', definition: 'A sudden and complete failure.', example: "The rushed rebrand became a debacle that took a year to recover from." },
  { id: 'w120', word: 'Flagrant', definition: 'Conspicuously and shockingly obvious.', example: "The flagrant policy breach left the company with no choice but to act publicly." },
  { id: 'w12', word: 'Ostensible', definition: 'Stated or appearing to be true, but not necessarily so.', example: "The ostensible reason for the delay was supply issues, though morale played a part too." },
  { id: 'w125', word: 'Gregarious', definition: 'Fond of company; sociable.', example: "Her gregarious nature made her the natural choice to run client events." },
  { id: 'w84', word: 'Diminutive', definition: 'Extremely or unusually small.', example: "The diminutive startup outmaneuvered three much larger competitors in a single quarter." },
  { id: 'w176', word: 'Mitigate', definition: 'To make less severe or serious.', example: "A clear rollback plan helped mitigate the risk of the big migration." },
  { id: 'w181', word: 'Nebulous', definition: 'Vague or unclear; poorly defined.', example: "The original brief was too nebulous for the design team to start real work." },
  { id: 'w119', word: 'Fervent', definition: 'Having or showing intense feeling.', example: "The founder remained a fervent believer in the mission through three failed pivots." },
  { id: 'w51', word: 'Capitulate', definition: 'To stop resisting and give in to a demand.', example: "After two rounds of pushback, the supplier finally capitulated on price." },
  { id: 'w155', word: 'Intransigent', definition: "Unwilling to change one's views or agree about something.", example: "The supplier stayed intransigent on price even after losing two other clients that month." },
  { id: 'w02', word: 'Ephemeral', definition: 'Lasting for a very short time.', example: "Quarterly wins can feel ephemeral if they're not built on a durable strategy." },
  { id: 'w55', word: 'Circuitous', definition: 'Longer and more indirect than a straight path.', example: "They took a circuitous route through three vendors before landing on the right one." },
  { id: 'w113', word: 'Explicit', definition: 'Stated clearly and in detail, leaving no room for confusion.', example: "The new contract was explicit about who owned the intellectual property." },
  { id: 'w169', word: 'Lucid', definition: 'Expressed clearly; easy to understand.', example: "His lucid explanation of the tax change saved the finance team an hour of confusion." },
  { id: 'w06', word: 'Pragmatic', definition: 'Dealing with things sensibly and realistically.', example: "A pragmatic leader chooses the achievable plan over the perfect one." },
  { id: 'w66', word: 'Contentious', definition: 'Likely to cause disagreement.', example: "Remote work policy remained the most contentious topic at every leadership offsite." },
  { id: 'w32', word: 'Adroit', definition: 'Clever and skillful, especially in handling difficult situations.', example: "He was adroit at turning a tense negotiation back into a collaborative one." },
  { id: 'w91', word: 'Duplicitous', definition: 'Deceitful; deliberately misleading.', example: "One duplicitous supplier quote was enough to end that entire partnership." },
  { id: 'w22', word: 'Candid', definition: 'Truthful and straightforward; frank.', example: "He gave candid feedback that the team badly needed." },
  { id: 'w183', word: 'Nonchalant', definition: 'Calm and casual, especially in a way that suggests indifference.', example: "He stayed nonchalant through the acquisition talks, which somehow made everyone else calmer too." },
  { id: 'w05', word: 'Nascent', definition: 'Just coming into existence; beginning to develop.', example: "The nascent partnership showed promise after just one meeting." },
  { id: 'w128', word: 'Hegemony', definition: 'Dominant influence or control over others.', example: "The company's early hegemony in the category made new entrants an afterthought." },
  { id: 'w158', word: 'Inured', definition: 'Accustomed to something unpleasant over time.', example: "After a dozen product launches, she was inured to last-minute chaos." },
  { id: 'w24', word: 'Diligent', definition: "Showing care and conscientiousness in one's work.", example: "Diligent preparation is what made the presentation land so well." },
  { id: 'w61', word: 'Congruent', definition: 'In agreement or harmony with something else.', example: "The new pricing needed to stay congruent with the brand's premium positioning." },
  { id: 'w162', word: 'Juxtapose', definition: 'To place side by side for contrasting effect.', example: "The deck juxtaposed last year's numbers with this year's to make the growth obvious." },
  { id: 'w57', word: 'Cohesive', definition: 'Forming a unified whole; sticking together well.', example: "A cohesive leadership team made the reorg far smoother than expected." },
  { id: 'w34', word: 'Ambivalent', definition: 'Having mixed or contradictory feelings about something.', example: "The board was ambivalent about the acquisition — excited by the upside, wary of the cost." },
  { id: 'w144', word: 'Incongruous', definition: 'Not in keeping with what is expected; out of place.', example: "The playful branding felt incongruous next to the product's enterprise price tag." },
  { id: 'w63', word: 'Consensus', definition: 'General agreement among a group.', example: "It took a long meeting, but the team reached consensus on the launch date." },
  { id: 'w97', word: 'Elicit', definition: 'To draw out a response or reaction.', example: "One well-placed question elicited the real objection the client had been avoiding." },
  { id: 'w118', word: 'Fastidious', definition: 'Very attentive to detail; hard to please.', example: "Their fastidious QA process is exactly why the app has near-zero crash reports." },
  { id: 'w79', word: 'Derivative', definition: 'Imitative of the work of someone else; unoriginal.', example: "The first pitch felt derivative of three other apps already on the market." },
  { id: 'w86', word: 'Disseminate', definition: 'To spread information widely.', example: "The policy change was disseminated to every regional office within a day." },
  { id: 'w148', word: 'Ingenuous', definition: 'Innocent and unsuspecting; artlessly straightforward.', example: "His ingenuous question about the roadmap turned out to be the smartest one asked." },
  { id: 'w111', word: 'Exigent', definition: 'Pressing; demanding immediate attention.', example: "The server outage was exigent enough to pull the whole engineering team off other work." },
  { id: 'w49', word: 'Cacophony', definition: 'A harsh, discordant mixture of sounds or opinions.', example: "The all-hands turned into a cacophony of conflicting priorities until she stepped in." },
  { id: 'w69', word: 'Cursory', definition: 'Hasty and without attention to detail.', example: "A cursory read of the contract nearly missed the auto-renewal clause." },
  { id: 'w83', word: 'Diffident', definition: 'Modest or shy due to lack of self-confidence.', example: "He was diffident in his first board presentation, but far sharper in the Q&A." },
  { id: 'w25', word: 'Meticulous', definition: 'Showing great attention to detail; very careful and precise.', example: "Her meticulous review of the contract caught a costly clause." },
  { id: 'w47', word: 'Bombastic', definition: 'High-sounding but with little substance; inflated.', example: "Investors saw through his bombastic pitch within the first five minutes." },
  { id: 'w29', word: 'Indefatigable', definition: 'Persisting tirelessly.', example: "His indefatigable energy carried the team through the final stretch of the launch." },
  { id: 'w147', word: 'Indolent', definition: 'Wanting to avoid activity or exertion; lazy.', example: "An indolent approach to follow-ups quietly lost them their best-fit lead." },
  { id: 'w130', word: 'Hierarchical', definition: 'Arranged in order of rank or authority.', example: "The flat structure worked well until scale forced a more hierarchical model." },
  { id: 'w38', word: 'Arbiter', definition: 'Someone with the power to settle a dispute or decide an outcome.', example: "As the final arbiter on design decisions, she broke the deadlock in minutes." },
  { id: 'w105', word: 'Equivocal', definition: 'Open to more than one interpretation; ambiguous.', example: "His equivocal answer left the whole room unsure if the deal was actually dead." },
  { id: 'w58', word: 'Complacent', definition: 'Showing uncritical satisfaction with oneself; self-satisfied.', example: "Market leaders that grow complacent are the ones a scrappy competitor eventually beats." },
  { id: 'w72', word: 'Decorum', definition: 'Behavior in good taste; propriety.', example: "She kept perfect decorum even when the client's tone turned sharp." },
  { id: 'w173', word: 'Malleable', definition: 'Easily influenced or shaped.', example: "Early-stage strategy needs to stay malleable as real customer data comes in." },
  { id: 'w102', word: 'Engender', definition: 'To cause or give rise to.', example: "Transparent pricing engendered a level of trust their competitors never built." },
  { id: 'w109', word: 'Exacerbate', definition: 'To make a problem or situation worse.', example: "Delaying the announcement only exacerbated the rumors already spreading internally." },
  { id: 'w145', word: 'Inculcate', definition: 'To instill an idea or habit through persistent instruction.', example: "New hires spend their first week having the safety-first culture inculcated in them." },
  { id: 'w43', word: 'Austere', definition: 'Plain, severe, or without luxury.', example: "The company kept an austere budget through its first two lean years." },
  { id: 'w142', word: 'Inadvertent', definition: 'Not resulting from careful thought; unintentional.', example: "The pricing bug was inadvertent, but the fallout still required a public statement." },
  { id: 'w110', word: 'Exculpate', definition: 'To show or declare that someone is not guilty.', example: "The audit fully exculpated the finance team from any wrongdoing." },
  { id: 'w157', word: 'Intrinsic', definition: 'Belonging naturally; essential to the core nature of something.', example: "The tool's intrinsic value was obvious the moment support tickets started dropping." },
  { id: 'w132', word: 'Hyperbole', definition: 'Exaggerated statements not meant to be taken literally.', example: "The press release leaned on hyperbole the investors quietly discounted." },
  { id: 'w37', word: 'Apposite', definition: 'Highly appropriate or relevant to what is being discussed.', example: "Her apposite example made the abstract strategy suddenly click for the whole room." },
  { id: 'w174', word: 'Mercurial', definition: 'Subject to sudden or unpredictable changes in mood.', example: "His mercurial temper made it hard for the team to know which version of him would show up." },
  { id: 'w45', word: 'Avuncular', definition: 'Kind and friendly toward younger or less experienced people, like an uncle.', example: "The retiring founder took an avuncular approach to mentoring the new CEO." },
  { id: 'w139', word: 'Imperious', definition: 'Assuming authority in a domineering way.', example: "His imperious tone in the vendor call cost more goodwill than the discount was worth." },
  { id: 'w59', word: 'Conciliatory', definition: 'Intended to placate or pacify.', example: "His conciliatory tone in the email cooled down a tense client thread fast." },
  { id: 'w134', word: 'Idiosyncratic', definition: 'Peculiar to an individual; distinctively unique.', example: "His idiosyncratic management style worked, though it never showed up in a textbook." },
  { id: 'w17', word: 'Magnanimous', definition: 'Generous or forgiving, especially toward a rival or less powerful person.', example: "She was magnanimous in victory, praising her competitor's product publicly." },
  { id: 'w133', word: 'Iconoclast', definition: 'A person who challenges established beliefs or conventions.', example: "As an iconoclast in a conservative industry, she rewrote the pricing playbook." },
  { id: 'w160', word: 'Inveterate', definition: 'Having a long-standing habit; deeply ingrained.', example: "He's an inveterate note-taker, and it's saved more than one client relationship." },
  { id: 'w48', word: 'Burgeoning', definition: 'Beginning to grow or increase rapidly.', example: "The burgeoning demand for the service outpaced their support team within weeks." },
  { id: 'w26', word: 'Resilient', definition: 'Able to withstand or recover quickly from difficult conditions.', example: "The most resilient teams treat setbacks as data, not verdicts." },
  { id: 'w177', word: 'Mollify', definition: 'To calm the anger of; to soothe.', example: "A same-day refund was enough to mollify most of the frustrated customers." },
  { id: 'w28', word: 'Discerning', definition: 'Showing good judgment, especially about taste or quality.', example: "A discerning eye for talent is one of her greatest strengths as a manager." },
  { id: 'w114', word: 'Exponential', definition: 'Increasing at a rate that accelerates over time.', example: "Referral signups grew exponentially once the reward was raised." },
  { id: 'w106', word: 'Erudite', definition: 'Having or showing great knowledge, learned.', example: "Her erudite grasp of tax law saved the company a costly structuring mistake." },
  { id: 'w10', word: 'Ameliorate', definition: 'To make something better or more tolerable.', example: "The new policy helped ameliorate tension between the two departments." },
  { id: 'w140', word: 'Implicit', definition: 'Suggested though not directly stated.', example: "There was an implicit expectation that senior staff would answer messages after hours." },
  { id: 'w11', word: 'Vindicate', definition: 'To clear someone of blame or suspicion; to prove correct.', example: "The results ultimately vindicated her unconventional strategy." },
  { id: 'w76', word: 'Demure', definition: 'Reserved, modest, and shy.', example: "He was demure about the win, crediting the whole team instead of himself." },
  { id: 'w75', word: 'Deft', definition: 'Neatly skillful and quick in action.', example: "A deft edit turned a rambling proposal into a two-page pitch." },
  { id: 'w100', word: 'Emulate', definition: 'To match or strive to match by imitation.', example: "Smaller competitors began to emulate the feature within a single release cycle." },
  { id: 'w73', word: 'Deference', definition: "Respectful submission to another's judgment.", example: "Junior staff showed too much deference to defend their own good ideas in the room." },
  { id: 'w92', word: 'Ebullient', definition: 'Cheerful and full of energy.', example: "She stayed ebullient through the entire investor roadshow, jet lag included." },
  { id: 'w78', word: 'Deprecate', definition: 'To express disapproval of, or to phase something out of use.', example: "The old reporting tool was quietly deprecated once the new dashboard shipped." },
  { id: 'w42', word: 'Auspicious', definition: 'Suggesting a good outcome; favorable.', example: "The pilot's early numbers were auspicious enough to greenlight a full rollout." },
  { id: 'w31', word: 'Acuity', definition: 'Sharpness of thought or perception.', example: "Her financial acuity spotted the margin problem two quarters before anyone else did." },
  { id: 'w121', word: 'Fractious', definition: 'Irritable and quarrelsome.', example: "The merger talks turned fractious the moment valuation came up." },
  { id: 'w21', word: 'Tenacious', definition: 'Tending to keep a firm hold; persistent.', example: "Her tenacious follow-up turned a cold lead into a signed contract." },
  { id: 'w04', word: 'Ubiquitous', definition: 'Present, appearing, or found everywhere.', example: "Video calls have become ubiquitous in modern leadership." },
  { id: 'w65', word: 'Constituent', definition: 'A necessary part of a whole; also, a member of a represented group.', example: "Trust turned out to be the single biggest constituent of customer loyalty." },
  { id: 'w03', word: 'Cogent', definition: 'Clear, logical, and convincing.', example: "He made a cogent case for delaying the product launch." },
  { id: 'w39', word: 'Articulate', definition: 'Able to express ideas clearly and effectively.', example: "He's the most articulate voice on the team when explaining technical risk to investors." },
  { id: 'w165', word: 'Lax', definition: 'Not sufficiently strict or careful.', example: "Lax password rules were the real reason the breach happened at all." },
  { id: 'w19', word: 'Prescient', definition: 'Having knowledge of events before they happen.', example: "His prescient warning about the market shift proved accurate within months." },
  { id: 'w180', word: 'Myriad', definition: 'A very great number of something.', example: "A myriad of small fixes did more for retention than the one big feature launch." },
  { id: 'w60', word: 'Conducive', definition: 'Making a certain outcome likely or easy.', example: "A quiet, no-meeting Friday proved far more conducive to deep work." },
  { id: 'w117', word: 'Facetious', definition: 'Treating a serious matter with inappropriate humor.', example: "His facetious comment landed badly in a meeting about layoffs." },
  { id: 'w33', word: 'Affable', definition: 'Friendly and easy to talk to.', example: "Her affable manner put even the most nervous new hires at ease." },
  { id: 'w170', word: 'Lucrative', definition: 'Producing a great deal of profit.', example: "The partnership turned out to be far more lucrative than either side expected." },
  { id: 'w159', word: 'Invective', definition: 'Harsh, abusive language directed at someone.', example: "The review turned into pure invective, with nothing useful for the team to act on." },
  { id: 'w154', word: 'Intractable', definition: 'Hard to control or resolve.', example: "The staffing shortage became an intractable problem no amount of overtime could fix." },
  { id: 'w94', word: 'Edify', definition: 'To instruct or improve morally or intellectually.', example: "The post-mortem was meant to edify the team, not assign blame." },
  { id: 'w81', word: 'Deter', definition: 'To discourage someone from doing something.', example: "A clear refund policy did more to deter chargebacks than any warning email." },
  { id: 'w85', word: 'Disparate', definition: 'Essentially different in kind; not comparable.', example: "Merging two disparate company cultures took far longer than merging the org charts." },
  { id: 'w01', word: 'Perspicacious', definition: 'Having keen insight or understanding; mentally sharp.', example: "Her perspicacious analysis of the market caught risks everyone else had missed." },
  { id: 'w151', word: 'Insidious', definition: 'Proceeding in a gradual, subtle way with harmful effects.', example: "Scope creep is insidious — nobody notices until the deadline is already gone." },
  { id: 'w152', word: 'Insipid', definition: 'Lacking flavor, vigor, or interest.', example: "The insipid tagline tested worse than no tagline at all." },
  { id: 'w116', word: 'Extrapolate', definition: 'To extend a conclusion based on known data to an unknown situation.', example: "It's risky to extrapolate next year's revenue from one strong quarter." },
  { id: 'w77', word: 'Denote', definition: 'To be a sign of; to indicate.', example: "A rising support ticket count usually denotes a bug, not a marketing win." },
  { id: 'w41', word: 'Assuage', definition: 'To make an unpleasant feeling less intense.', example: "A clear timeline helped assuage the client's concerns about the delay." },
  { id: 'w175', word: 'Meritorious', definition: 'Deserving reward or praise.', example: "Her meritorious handling of the crisis earned a promotion within the month." },
  { id: 'w101', word: 'Enervate', definition: 'To drain of energy or vitality.', example: "Back-to-back video calls all day tend to enervate a team faster than travel does." },
  { id: 'w53', word: 'Caveat', definition: 'A warning or qualification attached to a statement.', example: "He agreed to the timeline with one caveat — the design had to be locked first." },
  { id: 'w167', word: 'Liaison', definition: 'A person who acts as a link between groups.', example: "She became the informal liaison between engineering and the sales team." },
  { id: 'w127', word: 'Haphazard', definition: 'Lacking any obvious organization or plan.', example: "The haphazard rollout skipped half the training the support team needed." },
  { id: 'w153', word: 'Instigate', definition: 'To bring about or initiate, especially something contentious.', example: "One frustrated customer thread instigated a full review of the refund policy." },
  { id: 'w171', word: 'Luminary', definition: 'A person who inspires or influences others in a particular field.', example: "They brought in an industry luminary to advise on the international expansion." },
  { id: 'w08', word: 'Circumspect', definition: 'Wary and unwilling to take risks; cautious.', example: "Being circumspect about new hires saved the team from a costly mistake." },
  { id: 'w136', word: 'Impassive', definition: 'Not feeling or showing emotion.', example: "She stayed impassive through the hostile questioning, which unsettled the room more than anger would have." },
  { id: 'w46', word: 'Bolster', definition: 'To support or strengthen.', example: "The new testimonials helped bolster confidence in the product ahead of launch." },
  { id: 'w74', word: 'Deleterious', definition: 'Causing harm or damage.', example: "Skipping sleep for deadlines has a deleterious effect on decision quality within days." },
  { id: 'w138', word: 'Imperative', definition: 'Of vital importance; essential.', example: "Fixing the checkout bug became imperative the moment revenue started dipping." },
  { id: 'w141', word: 'Impute', definition: 'To attribute or ascribe a fault or quality to someone.', example: "It's easy to impute bad intent to a mistake that was really just poor process." },
  { id: 'w150', word: 'Innocuous', definition: 'Not harmful or offensive.', example: "What seemed like an innocuous UI tweak quietly broke three integrations." },
  { id: 'w18', word: 'Ineffable', definition: 'Too great or extreme to be expressed in words.', example: "There was an ineffable sense of relief when the deal finally closed." },
  { id: 'w44', word: 'Autonomous', definition: 'Independent and self-governing.', example: "Each regional team operates autonomously, reporting up only on quarterly targets." },
  { id: 'w62', word: 'Conjecture', definition: 'An opinion formed without complete evidence.', example: "Without the actual usage data, the churn theory was still just conjecture." },
  { id: 'w115', word: 'Extol', definition: 'To praise enthusiastically.', example: "The keynote extolled the team's resilience through a brutal product year." },
  { id: 'w122', word: 'Frugal', definition: 'Economical and sparing with money or resources.', example: "Staying frugal through the early years let them survive two funding droughts." },
  { id: 'w172', word: 'Malaise', definition: 'A general sense of unease or dissatisfaction.', example: "A quiet malaise settled over the team after the second round of layoffs." },
  { id: 'w50', word: 'Candor', definition: 'The quality of being open and honest.', example: "Her candor about the missed target earned more trust than a polished excuse would have." },
  { id: 'w40', word: 'Ascertain', definition: 'To find out something with certainty.', example: "It took three interviews to ascertain the real reason the last vendor was dropped." },
  { id: 'w09', word: 'Assiduous', definition: 'Showing great care and perseverance.', example: "His assiduous attention to detail caught the error before it shipped." },
  { id: 'w27', word: 'Acumen', definition: 'The ability to make good judgments and quick decisions.', example: "His business acumen turned a struggling division into the company's top performer." },
  { id: 'w93', word: 'Eclectic', definition: 'Deriving ideas from a broad and diverse range of sources.', example: "His eclectic reading habits are exactly why he spots trends before competitors do." },
  { id: 'w123', word: 'Garrulous', definition: 'Excessively talkative, especially about trivial matters.', example: "The garrulous vendor rep talked for twenty minutes before mentioning the price." },
  { id: 'w135', word: 'Immutable', definition: 'Unchanging over time; unable to be altered.', example: "The company's core values stayed immutable through every rebrand and reorg." },
  { id: 'w126', word: 'Hackneyed', definition: 'Lacking originality due to overuse.', example: "The pitch leaned on hackneyed phrases like 'disruptive' and 'best-in-class'." },
  { id: 'w166', word: 'Lethargic', definition: 'Lacking energy; sluggish.', example: "The team felt lethargic after three straight weeks of overlapping deadlines." },
  { id: 'w95', word: 'Efficacious', definition: 'Successful in producing the intended result.', example: "A short daily standup proved more efficacious than the old weekly status email." },
  { id: 'w107', word: 'Esoteric', definition: 'Intended for or understood by only a small, specialized group.', example: "The compliance detail was too esoteric for the all-hands, but essential for legal." },
];

function getTodaysWord(dayIndex) {
  return WORDS[dayIndex % WORDS.length];
}

if (typeof window !== 'undefined') {
  window.WORDS = WORDS;
  window.getTodaysWord = getTodaysWord;
}
